// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: simulator.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMaliciousActionType int32

const (
	NodeMaliciousActionType_CorruptPacket NodeMaliciousActionType = 0
	NodeMaliciousActionType_DropPacket    NodeMaliciousActionType = 1
)

// Enum value maps for NodeMaliciousActionType.
var (
	NodeMaliciousActionType_name = map[int32]string{
		0: "CorruptPacket",
		1: "DropPacket",
	}
	NodeMaliciousActionType_value = map[string]int32{
		"CorruptPacket": 0,
		"DropPacket":    1,
	}
)

func (x NodeMaliciousActionType) Enum() *NodeMaliciousActionType {
	p := new(NodeMaliciousActionType)
	*p = x
	return p
}

func (x NodeMaliciousActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeMaliciousActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[0].Descriptor()
}

func (NodeMaliciousActionType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[0]
}

func (x NodeMaliciousActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeMaliciousActionType.Descriptor instead.
func (NodeMaliciousActionType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{0}
}

type SimNetworkNodeType int32

const (
	SimNetworkNodeType_NormalRouter         SimNetworkNodeType = 0
	SimNetworkNodeType_PathValidationRouter SimNetworkNodeType = 1
)

// Enum value maps for SimNetworkNodeType.
var (
	SimNetworkNodeType_name = map[int32]string{
		0: "NormalRouter",
		1: "PathValidationRouter",
	}
	SimNetworkNodeType_value = map[string]int32{
		"NormalRouter":         0,
		"PathValidationRouter": 1,
	}
)

func (x SimNetworkNodeType) Enum() *SimNetworkNodeType {
	p := new(SimNetworkNodeType)
	*p = x
	return p
}

func (x SimNetworkNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimNetworkNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[1].Descriptor()
}

func (SimNetworkNodeType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[1]
}

func (x SimNetworkNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimNetworkNodeType.Descriptor instead.
func (SimNetworkNodeType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{1}
}

type SimDirectedLinkType int32

const (
	SimDirectedLinkType_SimDirectedPvLink     SimDirectedLinkType = 0
	SimDirectedLinkType_SimDirectedNormalLink SimDirectedLinkType = 1
)

// Enum value maps for SimDirectedLinkType.
var (
	SimDirectedLinkType_name = map[int32]string{
		0: "SimDirectedPvLink",
		1: "SimDirectedNormalLink",
	}
	SimDirectedLinkType_value = map[string]int32{
		"SimDirectedPvLink":     0,
		"SimDirectedNormalLink": 1,
	}
)

func (x SimDirectedLinkType) Enum() *SimDirectedLinkType {
	p := new(SimDirectedLinkType)
	*p = x
	return p
}

func (x SimDirectedLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimDirectedLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[2].Descriptor()
}

func (SimDirectedLinkType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[2]
}

func (x SimDirectedLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimDirectedLinkType.Descriptor instead.
func (SimDirectedLinkType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{2}
}

var File_simulator_proto protoreflect.FileDescriptor

const file_simulator_proto_rawDesc = "" +
	"\n" +
	"\x0fsimulator.proto*<\n" +
	"\x17NodeMaliciousActionType\x12\x11\n" +
	"\rCorruptPacket\x10\x00\x12\x0e\n" +
	"\n" +
	"DropPacket\x10\x01*@\n" +
	"\x12SimNetworkNodeType\x12\x10\n" +
	"\fNormalRouter\x10\x00\x12\x18\n" +
	"\x14PathValidationRouter\x10\x01*G\n" +
	"\x13SimDirectedLinkType\x12\x15\n" +
	"\x11SimDirectedPvLink\x10\x00\x12\x19\n" +
	"\x15SimDirectedNormalLink\x10\x01B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_simulator_proto_rawDescOnce sync.Once
	file_simulator_proto_rawDescData []byte
)

func file_simulator_proto_rawDescGZIP() []byte {
	file_simulator_proto_rawDescOnce.Do(func() {
		file_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)))
	})
	return file_simulator_proto_rawDescData
}

var file_simulator_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_simulator_proto_goTypes = []any{
	(NodeMaliciousActionType)(0), // 0: NodeMaliciousActionType
	(SimNetworkNodeType)(0),      // 1: SimNetworkNodeType
	(SimDirectedLinkType)(0),     // 2: SimDirectedLinkType
}
var file_simulator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simulator_proto_init() }
func file_simulator_proto_init() {
	if File_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simulator_proto_goTypes,
		DependencyIndexes: file_simulator_proto_depIdxs,
		EnumInfos:         file_simulator_proto_enumTypes,
	}.Build()
	File_simulator_proto = out.File
	file_simulator_proto_goTypes = nil
	file_simulator_proto_depIdxs = nil
}
