// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: simulator.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimPacketType int32

const (
	SimPacketType_DataPacket SimPacketType = 0
	SimPacketType_AckPacket  SimPacketType = 1
)

// Enum value maps for SimPacketType.
var (
	SimPacketType_name = map[int32]string{
		0: "DataPacket",
		1: "AckPacket",
	}
	SimPacketType_value = map[string]int32{
		"DataPacket": 0,
		"AckPacket":  1,
	}
)

func (x SimPacketType) Enum() *SimPacketType {
	p := new(SimPacketType)
	*p = x
	return p
}

func (x SimPacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimPacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[0].Descriptor()
}

func (SimPacketType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[0]
}

func (x SimPacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimPacketType.Descriptor instead.
func (SimPacketType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{0}
}

type NodeMaliciousActionType int32

const (
	NodeMaliciousActionType_CorruptPacket NodeMaliciousActionType = 0
	NodeMaliciousActionType_DropPacket    NodeMaliciousActionType = 1
)

// Enum value maps for NodeMaliciousActionType.
var (
	NodeMaliciousActionType_name = map[int32]string{
		0: "CorruptPacket",
		1: "DropPacket",
	}
	NodeMaliciousActionType_value = map[string]int32{
		"CorruptPacket": 0,
		"DropPacket":    1,
	}
)

func (x NodeMaliciousActionType) Enum() *NodeMaliciousActionType {
	p := new(NodeMaliciousActionType)
	*p = x
	return p
}

func (x NodeMaliciousActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeMaliciousActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[1].Descriptor()
}

func (NodeMaliciousActionType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[1]
}

func (x NodeMaliciousActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeMaliciousActionType.Descriptor instead.
func (NodeMaliciousActionType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{1}
}

type SimNetworkNodeType int32

const (
	SimNetworkNodeType_EndHost              SimNetworkNodeType = 0
	SimNetworkNodeType_NormalRouter         SimNetworkNodeType = 1
	SimNetworkNodeType_PathValidationRouter SimNetworkNodeType = 2
)

// Enum value maps for SimNetworkNodeType.
var (
	SimNetworkNodeType_name = map[int32]string{
		0: "EndHost",
		1: "NormalRouter",
		2: "PathValidationRouter",
	}
	SimNetworkNodeType_value = map[string]int32{
		"EndHost":              0,
		"NormalRouter":         1,
		"PathValidationRouter": 2,
	}
)

func (x SimNetworkNodeType) Enum() *SimNetworkNodeType {
	p := new(SimNetworkNodeType)
	*p = x
	return p
}

func (x SimNetworkNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimNetworkNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[2].Descriptor()
}

func (SimNetworkNodeType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[2]
}

func (x SimNetworkNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimNetworkNodeType.Descriptor instead.
func (SimNetworkNodeType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{2}
}

type SimDirectedLinkType int32

const (
	SimDirectedLinkType_SimDirectedNormalLink SimDirectedLinkType = 0
	SimDirectedLinkType_SimDirectedPvLink     SimDirectedLinkType = 1
	SimDirectedLinkType_SimDirectedAccessLink SimDirectedLinkType = 2
)

// Enum value maps for SimDirectedLinkType.
var (
	SimDirectedLinkType_name = map[int32]string{
		0: "SimDirectedNormalLink",
		1: "SimDirectedPvLink",
		2: "SimDirectedAccessLink",
	}
	SimDirectedLinkType_value = map[string]int32{
		"SimDirectedNormalLink": 0,
		"SimDirectedPvLink":     1,
		"SimDirectedAccessLink": 2,
	}
)

func (x SimDirectedLinkType) Enum() *SimDirectedLinkType {
	p := new(SimDirectedLinkType)
	*p = x
	return p
}

func (x SimDirectedLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimDirectedLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[3].Descriptor()
}

func (SimDirectedLinkType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[3]
}

func (x SimDirectedLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimDirectedLinkType.Descriptor instead.
func (SimDirectedLinkType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{3}
}

type SimRecorderType int32

const (
	SimRecorderType_BloomFilterRecorder SimRecorderType = 0
	SimRecorderType_CountRecorder       SimRecorderType = 1
)

// Enum value maps for SimRecorderType.
var (
	SimRecorderType_name = map[int32]string{
		0: "BloomFilterRecorder",
		1: "CountRecorder",
	}
	SimRecorderType_value = map[string]int32{
		"BloomFilterRecorder": 0,
		"CountRecorder":       1,
	}
)

func (x SimRecorderType) Enum() *SimRecorderType {
	p := new(SimRecorderType)
	*p = x
	return p
}

func (x SimRecorderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimRecorderType) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[4].Descriptor()
}

func (SimRecorderType) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[4]
}

func (x SimRecorderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimRecorderType.Descriptor instead.
func (SimRecorderType) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{4}
}

type GainCalculationMode int32

const (
	GainCalculationMode_SumEdgeGains          GainCalculationMode = 0
	GainCalculationMode_SumEdgeAndRouterGains GainCalculationMode = 1
)

// Enum value maps for GainCalculationMode.
var (
	GainCalculationMode_name = map[int32]string{
		0: "SumEdgeGains",
		1: "SumEdgeAndRouterGains",
	}
	GainCalculationMode_value = map[string]int32{
		"SumEdgeGains":          0,
		"SumEdgeAndRouterGains": 1,
	}
)

func (x GainCalculationMode) Enum() *GainCalculationMode {
	p := new(GainCalculationMode)
	*p = x
	return p
}

func (x GainCalculationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GainCalculationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[5].Descriptor()
}

func (GainCalculationMode) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[5]
}

func (x GainCalculationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GainCalculationMode.Descriptor instead.
func (GainCalculationMode) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{5}
}

type SimStrategy int32

const (
	SimStrategy_PerBatchBloomFilter SimStrategy = 0
	SimStrategy_PerPacketAck        SimStrategy = 1
)

// Enum value maps for SimStrategy.
var (
	SimStrategy_name = map[int32]string{
		0: "PerBatchBloomFilter",
		1: "PerPacketAck",
	}
	SimStrategy_value = map[string]int32{
		"PerBatchBloomFilter": 0,
		"PerPacketAck":        1,
	}
)

func (x SimStrategy) Enum() *SimStrategy {
	p := new(SimStrategy)
	*p = x
	return p
}

func (x SimStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[6].Descriptor()
}

func (SimStrategy) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[6]
}

func (x SimStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimStrategy.Descriptor instead.
func (SimStrategy) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{6}
}

type SimAlgorithm int32

const (
	SimAlgorithm_Exp3 SimAlgorithm = 0
	SimAlgorithm_OSMD SimAlgorithm = 1
)

// Enum value maps for SimAlgorithm.
var (
	SimAlgorithm_name = map[int32]string{
		0: "Exp3",
		1: "OSMD",
	}
	SimAlgorithm_value = map[string]int32{
		"Exp3": 0,
		"OSMD": 1,
	}
)

func (x SimAlgorithm) Enum() *SimAlgorithm {
	p := new(SimAlgorithm)
	*p = x
	return p
}

func (x SimAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_proto_enumTypes[7].Descriptor()
}

func (SimAlgorithm) Type() protoreflect.EnumType {
	return &file_simulator_proto_enumTypes[7]
}

func (x SimAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimAlgorithm.Descriptor instead.
func (SimAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{7}
}

var File_simulator_proto protoreflect.FileDescriptor

const file_simulator_proto_rawDesc = "" +
	"\n" +
	"\x0fsimulator.proto*.\n" +
	"\rSimPacketType\x12\x0e\n" +
	"\n" +
	"DataPacket\x10\x00\x12\r\n" +
	"\tAckPacket\x10\x01*<\n" +
	"\x17NodeMaliciousActionType\x12\x11\n" +
	"\rCorruptPacket\x10\x00\x12\x0e\n" +
	"\n" +
	"DropPacket\x10\x01*M\n" +
	"\x12SimNetworkNodeType\x12\v\n" +
	"\aEndHost\x10\x00\x12\x10\n" +
	"\fNormalRouter\x10\x01\x12\x18\n" +
	"\x14PathValidationRouter\x10\x02*b\n" +
	"\x13SimDirectedLinkType\x12\x19\n" +
	"\x15SimDirectedNormalLink\x10\x00\x12\x15\n" +
	"\x11SimDirectedPvLink\x10\x01\x12\x19\n" +
	"\x15SimDirectedAccessLink\x10\x02*=\n" +
	"\x0fSimRecorderType\x12\x17\n" +
	"\x13BloomFilterRecorder\x10\x00\x12\x11\n" +
	"\rCountRecorder\x10\x01*B\n" +
	"\x13GainCalculationMode\x12\x10\n" +
	"\fSumEdgeGains\x10\x00\x12\x19\n" +
	"\x15SumEdgeAndRouterGains\x10\x01*8\n" +
	"\vSimStrategy\x12\x17\n" +
	"\x13PerBatchBloomFilter\x10\x00\x12\x10\n" +
	"\fPerPacketAck\x10\x01*\"\n" +
	"\fSimAlgorithm\x12\b\n" +
	"\x04Exp3\x10\x00\x12\b\n" +
	"\x04OSMD\x10\x01B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_simulator_proto_rawDescOnce sync.Once
	file_simulator_proto_rawDescData []byte
)

func file_simulator_proto_rawDescGZIP() []byte {
	file_simulator_proto_rawDescOnce.Do(func() {
		file_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)))
	})
	return file_simulator_proto_rawDescData
}

var file_simulator_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_simulator_proto_goTypes = []any{
	(SimPacketType)(0),           // 0: SimPacketType
	(NodeMaliciousActionType)(0), // 1: NodeMaliciousActionType
	(SimNetworkNodeType)(0),      // 2: SimNetworkNodeType
	(SimDirectedLinkType)(0),     // 3: SimDirectedLinkType
	(SimRecorderType)(0),         // 4: SimRecorderType
	(GainCalculationMode)(0),     // 5: GainCalculationMode
	(SimStrategy)(0),             // 6: SimStrategy
	(SimAlgorithm)(0),            // 7: SimAlgorithm
}
var file_simulator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simulator_proto_init() }
func file_simulator_proto_init() {
	if File_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simulator_proto_goTypes,
		DependencyIndexes: file_simulator_proto_depIdxs,
		EnumInfos:         file_simulator_proto_enumTypes,
	}.Build()
	File_simulator_proto = out.File
	file_simulator_proto_goTypes = nil
	file_simulator_proto_depIdxs = nil
}
