// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: protobuf/interact.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NormalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *NormalResponse) Reset() {
	*x = NormalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalResponse) ProtoMessage() {}

func (x *NormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalResponse.ProtoReflect.Descriptor instead.
func (*NormalResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{0}
}

func (x *NormalResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

// 请求消息
type SetAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceName string `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	InterfaceAddr string `protobuf:"bytes,2,opt,name=interfaceAddr,proto3" json:"interfaceAddr,omitempty"`
}

func (x *SetAddrRequest) Reset() {
	*x = SetAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddrRequest) ProtoMessage() {}

func (x *SetAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddrRequest.ProtoReflect.Descriptor instead.
func (*SetAddrRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{1}
}

func (x *SetAddrRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetAddrRequest) GetInterfaceAddr() string {
	if x != nil {
		return x.InterfaceAddr
	}
	return ""
}

// 添加路由消息
type AddRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestinationNetworkSegment string `protobuf:"bytes,1,opt,name=destinationNetworkSegment,proto3" json:"destinationNetworkSegment,omitempty"`
	Gateway                   string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{2}
}

func (x *AddRouteRequest) GetDestinationNetworkSegment() string {
	if x != nil {
		return x.DestinationNetworkSegment
	}
	return ""
}

func (x *AddRouteRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

// 文件传输消息
type TransmitFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestinationPath string `protobuf:"bytes,1,opt,name=destinationPath,proto3" json:"destinationPath,omitempty"`
	Content         string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *TransmitFileRequest) Reset() {
	*x = TransmitFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransmitFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitFileRequest) ProtoMessage() {}

func (x *TransmitFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitFileRequest.ProtoReflect.Descriptor instead.
func (*TransmitFileRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{3}
}

func (x *TransmitFileRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *TransmitFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LoadKernelInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadKernelInfoRequest) Reset() {
	*x = LoadKernelInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadKernelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKernelInfoRequest) ProtoMessage() {}

func (x *LoadKernelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKernelInfoRequest.ProtoReflect.Descriptor instead.
func (*LoadKernelInfoRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{4}
}

// 设置环境变量消息
type SetEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvFields []string `protobuf:"bytes,1,rep,name=envFields,proto3" json:"envFields,omitempty"`
	EnvValues []string `protobuf:"bytes,2,rep,name=envValues,proto3" json:"envValues,omitempty"`
}

func (x *SetEnvRequest) Reset() {
	*x = SetEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_interact_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnvRequest) ProtoMessage() {}

func (x *SetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_interact_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnvRequest.ProtoReflect.Descriptor instead.
func (*SetEnvRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_interact_proto_rawDescGZIP(), []int{5}
}

func (x *SetEnvRequest) GetEnvFields() []string {
	if x != nil {
		return x.EnvFields
	}
	return nil
}

func (x *SetEnvRequest) GetEnvValues() []string {
	if x != nil {
		return x.EnvValues
	}
	return nil
}

var File_protobuf_interact_proto protoreflect.FileDescriptor

var file_protobuf_interact_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x26, 0x0a, 0x0e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x5c, 0x0a, 0x0e, 0x53,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x69, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x19,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x19, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x22, 0x59, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x4c, 0x6f, 0x61, 0x64, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x45,
	0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x76,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e,
	0x76, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x76, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x76, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0xe7, 0x02, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x3f, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d,
	0x69, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x12, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x5e, 0x5a, 0x5c, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x68, 0x65, 0x66, 0x61, 0x6e, 0x31, 0x32, 0x33,
	0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2f, 0x72, 0x61, 0x73, 0x70, 0x62, 0x65, 0x72, 0x72, 0x79, 0x70, 0x69, 0x5f, 0x74, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_interact_proto_rawDescOnce sync.Once
	file_protobuf_interact_proto_rawDescData = file_protobuf_interact_proto_rawDesc
)

func file_protobuf_interact_proto_rawDescGZIP() []byte {
	file_protobuf_interact_proto_rawDescOnce.Do(func() {
		file_protobuf_interact_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_interact_proto_rawDescData)
	})
	return file_protobuf_interact_proto_rawDescData
}

var file_protobuf_interact_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_interact_proto_goTypes = []any{
	(*NormalResponse)(nil),        // 0: protobuf.NormalResponse
	(*SetAddrRequest)(nil),        // 1: protobuf.SetAddrRequest
	(*AddRouteRequest)(nil),       // 2: protobuf.AddRouteRequest
	(*TransmitFileRequest)(nil),   // 3: protobuf.TransmitFileRequest
	(*LoadKernelInfoRequest)(nil), // 4: protobuf.LoadKernelInfoRequest
	(*SetEnvRequest)(nil),         // 5: protobuf.SetEnvRequest
}
var file_protobuf_interact_proto_depIdxs = []int32{
	1, // 0: protobuf.Interact.SetAddr:input_type -> protobuf.SetAddrRequest
	2, // 1: protobuf.Interact.AddRoute:input_type -> protobuf.AddRouteRequest
	3, // 2: protobuf.Interact.TransmitFile:input_type -> protobuf.TransmitFileRequest
	5, // 3: protobuf.Interact.SetEnv:input_type -> protobuf.SetEnvRequest
	4, // 4: protobuf.Interact.LoadKernelInfo:input_type -> protobuf.LoadKernelInfoRequest
	0, // 5: protobuf.Interact.SetAddr:output_type -> protobuf.NormalResponse
	0, // 6: protobuf.Interact.AddRoute:output_type -> protobuf.NormalResponse
	0, // 7: protobuf.Interact.TransmitFile:output_type -> protobuf.NormalResponse
	0, // 8: protobuf.Interact.SetEnv:output_type -> protobuf.NormalResponse
	0, // 9: protobuf.Interact.LoadKernelInfo:output_type -> protobuf.NormalResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_interact_proto_init() }
func file_protobuf_interact_proto_init() {
	if File_protobuf_interact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_interact_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NormalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_interact_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_interact_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_interact_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TransmitFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_interact_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LoadKernelInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_interact_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_interact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_interact_proto_goTypes,
		DependencyIndexes: file_protobuf_interact_proto_depIdxs,
		MessageInfos:      file_protobuf_interact_proto_msgTypes,
	}.Build()
	File_protobuf_interact_proto = out.File
	file_protobuf_interact_proto_rawDesc = nil
	file_protobuf_interact_proto_goTypes = nil
	file_protobuf_interact_proto_depIdxs = nil
}
