// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: chain.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainType int32

const (
	ChainType_NonChain          ChainType = 0
	ChainType_ChainMaker        ChainType = 1
	ChainType_HyperledgerFabric ChainType = 2
	ChainType_FiscoBcos         ChainType = 3
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "NonChain",
		1: "ChainMaker",
		2: "HyperledgerFabric",
		3: "FiscoBcos",
	}
	ChainType_value = map[string]int32{
		"NonChain":          0,
		"ChainMaker":        1,
		"HyperledgerFabric": 2,
		"FiscoBcos":         3,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[0].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[0]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

var File_chain_proto protoreflect.FileDescriptor

const file_chain_proto_rawDesc = "" +
	"\n" +
	"\vchain.proto*O\n" +
	"\tChainType\x12\f\n" +
	"\bNonChain\x10\x00\x12\x0e\n" +
	"\n" +
	"ChainMaker\x10\x01\x12\x15\n" +
	"\x11HyperledgerFabric\x10\x02\x12\r\n" +
	"\tFiscoBcos\x10\x03B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_chain_proto_rawDescOnce sync.Once
	file_chain_proto_rawDescData []byte
)

func file_chain_proto_rawDescGZIP() []byte {
	file_chain_proto_rawDescOnce.Do(func() {
		file_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)))
	})
	return file_chain_proto_rawDescData
}

var file_chain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chain_proto_goTypes = []any{
	(ChainType)(0), // 0: ChainType
}
var file_chain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chain_proto_init() }
func file_chain_proto_init() {
	if File_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_proto_goTypes,
		DependencyIndexes: file_chain_proto_depIdxs,
		EnumInfos:         file_chain_proto_enumTypes,
	}.Build()
	File_chain_proto = out.File
	file_chain_proto_goTypes = nil
	file_chain_proto_depIdxs = nil
}
