// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.20.3
// source: entities.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NetworkNodeStatus int32

const (
	NetworkNodeStatus_Logic   NetworkNodeStatus = 0 // 逻辑上的内存对象
	NetworkNodeStatus_Created NetworkNodeStatus = 1 // 创建状态
	NetworkNodeStatus_STOPPED NetworkNodeStatus = 2 // 停止状态 -> 中间状态
	NetworkNodeStatus_Started NetworkNodeStatus = 3 // 启动状态
)

// Enum value maps for NetworkNodeStatus.
var (
	NetworkNodeStatus_name = map[int32]string{
		0: "Logic",
		1: "Created",
		2: "STOPPED",
		3: "Started",
	}
	NetworkNodeStatus_value = map[string]int32{
		"Logic":   0,
		"Created": 1,
		"STOPPED": 2,
		"Started": 3,
	}
)

func (x NetworkNodeStatus) Enum() *NetworkNodeStatus {
	p := new(NetworkNodeStatus)
	*p = x
	return p
}

func (x NetworkNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[0].Descriptor()
}

func (NetworkNodeStatus) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[0]
}

func (x NetworkNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkNodeStatus.Descriptor instead.
func (NetworkNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

type NetworkNodeType int32

const (
	NetworkNodeType_NormalSatellite    NetworkNodeType = 0
	NetworkNodeType_ConsensusSatellite NetworkNodeType = 1
	NetworkNodeType_EtcdService        NetworkNodeType = 2
	NetworkNodeType_PositionService    NetworkNodeType = 3
	NetworkNodeType_Router             NetworkNodeType = 4
	NetworkNodeType_NormalNode         NetworkNodeType = 5
	NetworkNodeType_ConsensusNode      NetworkNodeType = 6
	NetworkNodeType_ChainMakerNode     NetworkNodeType = 7
	NetworkNodeType_MaliciousNode      NetworkNodeType = 8
	NetworkNodeType_LirNode            NetworkNodeType = 9
	NetworkNodeType_Entrance           NetworkNodeType = 10
)

// Enum value maps for NetworkNodeType.
var (
	NetworkNodeType_name = map[int32]string{
		0:  "NormalSatellite",
		1:  "ConsensusSatellite",
		2:  "EtcdService",
		3:  "PositionService",
		4:  "Router",
		5:  "NormalNode",
		6:  "ConsensusNode",
		7:  "ChainMakerNode",
		8:  "MaliciousNode",
		9:  "LirNode",
		10: "Entrance",
	}
	NetworkNodeType_value = map[string]int32{
		"NormalSatellite":    0,
		"ConsensusSatellite": 1,
		"EtcdService":        2,
		"PositionService":    3,
		"Router":             4,
		"NormalNode":         5,
		"ConsensusNode":      6,
		"ChainMakerNode":     7,
		"MaliciousNode":      8,
		"LirNode":            9,
		"Entrance":           10,
	}
)

func (x NetworkNodeType) Enum() *NetworkNodeType {
	p := new(NetworkNodeType)
	*p = x
	return p
}

func (x NetworkNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[1].Descriptor()
}

func (NetworkNodeType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[1]
}

func (x NetworkNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkNodeType.Descriptor instead.
func (NetworkNodeType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{1}
}

type NetworkLinkType int32

const (
	NetworkLinkType_IntraOrbitSatelliteLink NetworkLinkType = 0
	NetworkLinkType_InterOrbitSatelliteLink NetworkLinkType = 1
	NetworkLinkType_AccessLink              NetworkLinkType = 2
	NetworkLinkType_BackboneLink            NetworkLinkType = 3
)

// Enum value maps for NetworkLinkType.
var (
	NetworkLinkType_name = map[int32]string{
		0: "IntraOrbitSatelliteLink",
		1: "InterOrbitSatelliteLink",
		2: "AccessLink",
		3: "BackboneLink",
	}
	NetworkLinkType_value = map[string]int32{
		"IntraOrbitSatelliteLink": 0,
		"InterOrbitSatelliteLink": 1,
		"AccessLink":              2,
		"BackboneLink":            3,
	}
)

func (x NetworkLinkType) Enum() *NetworkLinkType {
	p := new(NetworkLinkType)
	*p = x
	return p
}

func (x NetworkLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[2].Descriptor()
}

func (NetworkLinkType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[2]
}

func (x NetworkLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkLinkType.Descriptor instead.
func (NetworkLinkType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{2}
}

var File_entities_proto protoreflect.FileDescriptor

var file_entities_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x45, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x03, 0x2a, 0xd5, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x61, 0x74,
	0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x74, 0x63, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x10, 0x06, 0x12, 0x12, 0x0a,
	0x0e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x10,
	0x07, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x61, 0x6c, 0x69, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x4e, 0x6f,
	0x64, 0x65, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x10,
	0x09, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x0a, 0x2a,
	0x6d, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x4f, 0x72, 0x62, 0x69, 0x74,
	0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x53, 0x61, 0x74,
	0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x42, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x10, 0x03, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_entities_proto_rawDescOnce sync.Once
	file_entities_proto_rawDescData = file_entities_proto_rawDesc
)

func file_entities_proto_rawDescGZIP() []byte {
	file_entities_proto_rawDescOnce.Do(func() {
		file_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_entities_proto_rawDescData)
	})
	return file_entities_proto_rawDescData
}

var file_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_entities_proto_goTypes = []interface{}{
	(NetworkNodeStatus)(0), // 0: NetworkNodeStatus
	(NetworkNodeType)(0),   // 1: NetworkNodeType
	(NetworkLinkType)(0),   // 2: NetworkLinkType
}
var file_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_proto_init() }
func file_entities_proto_init() {
	if File_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entities_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_proto_goTypes,
		DependencyIndexes: file_entities_proto_depIdxs,
		EnumInfos:         file_entities_proto_enumTypes,
	}.Build()
	File_entities_proto = out.File
	file_entities_proto_rawDesc = nil
	file_entities_proto_goTypes = nil
	file_entities_proto_depIdxs = nil
}
