// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: entities.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkNodeStatus int32

const (
	NetworkNodeStatus_Logic   NetworkNodeStatus = 0 // 逻辑上的内存对象
	NetworkNodeStatus_Created NetworkNodeStatus = 1 // 创建状态
	NetworkNodeStatus_STOPPED NetworkNodeStatus = 2 // 停止状态 -> 中间状态
	NetworkNodeStatus_Started NetworkNodeStatus = 3 // 启动状态
)

// Enum value maps for NetworkNodeStatus.
var (
	NetworkNodeStatus_name = map[int32]string{
		0: "Logic",
		1: "Created",
		2: "STOPPED",
		3: "Started",
	}
	NetworkNodeStatus_value = map[string]int32{
		"Logic":   0,
		"Created": 1,
		"STOPPED": 2,
		"Started": 3,
	}
)

func (x NetworkNodeStatus) Enum() *NetworkNodeStatus {
	p := new(NetworkNodeStatus)
	*p = x
	return p
}

func (x NetworkNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[0].Descriptor()
}

func (NetworkNodeStatus) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[0]
}

func (x NetworkNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkNodeStatus.Descriptor instead.
func (NetworkNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

type NetworkNodeType int32

const (
	NetworkNodeType_NormalSatellite NetworkNodeType = 0
	NetworkNodeType_EtcdService     NetworkNodeType = 1
	NetworkNodeType_PositionService NetworkNodeType = 2
	NetworkNodeType_Router          NetworkNodeType = 3
	NetworkNodeType_NormalNode      NetworkNodeType = 4
	NetworkNodeType_ConsensusNode   NetworkNodeType = 5
	NetworkNodeType_ChainMakerNode  NetworkNodeType = 6
	NetworkNodeType_MaliciousNode   NetworkNodeType = 7
	NetworkNodeType_LirNode         NetworkNodeType = 8
	NetworkNodeType_Entrance        NetworkNodeType = 9
	NetworkNodeType_GroundStation   NetworkNodeType = 10
	NetworkNodeType_FabricPeerNode  NetworkNodeType = 11
	NetworkNodeType_FabricOrderNode NetworkNodeType = 12
	NetworkNodeType_LiRSatellite    NetworkNodeType = 13
	NetworkNodeType_FiscoBcosNode   NetworkNodeType = 14
)

// Enum value maps for NetworkNodeType.
var (
	NetworkNodeType_name = map[int32]string{
		0:  "NormalSatellite",
		1:  "EtcdService",
		2:  "PositionService",
		3:  "Router",
		4:  "NormalNode",
		5:  "ConsensusNode",
		6:  "ChainMakerNode",
		7:  "MaliciousNode",
		8:  "LirNode",
		9:  "Entrance",
		10: "GroundStation",
		11: "FabricPeerNode",
		12: "FabricOrderNode",
		13: "LiRSatellite",
		14: "FiscoBcosNode",
	}
	NetworkNodeType_value = map[string]int32{
		"NormalSatellite": 0,
		"EtcdService":     1,
		"PositionService": 2,
		"Router":          3,
		"NormalNode":      4,
		"ConsensusNode":   5,
		"ChainMakerNode":  6,
		"MaliciousNode":   7,
		"LirNode":         8,
		"Entrance":        9,
		"GroundStation":   10,
		"FabricPeerNode":  11,
		"FabricOrderNode": 12,
		"LiRSatellite":    13,
		"FiscoBcosNode":   14,
	}
)

func (x NetworkNodeType) Enum() *NetworkNodeType {
	p := new(NetworkNodeType)
	*p = x
	return p
}

func (x NetworkNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[1].Descriptor()
}

func (NetworkNodeType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[1]
}

func (x NetworkNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkNodeType.Descriptor instead.
func (NetworkNodeType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{1}
}

type NetworkLinkType int32

const (
	NetworkLinkType_IntraOrbitSatelliteLink NetworkLinkType = 0
	NetworkLinkType_InterOrbitSatelliteLink NetworkLinkType = 1
	NetworkLinkType_GroundSatelliteLink     NetworkLinkType = 2
	NetworkLinkType_AccessLink              NetworkLinkType = 3
	NetworkLinkType_BackboneLink            NetworkLinkType = 4
)

// Enum value maps for NetworkLinkType.
var (
	NetworkLinkType_name = map[int32]string{
		0: "IntraOrbitSatelliteLink",
		1: "InterOrbitSatelliteLink",
		2: "GroundSatelliteLink",
		3: "AccessLink",
		4: "BackboneLink",
	}
	NetworkLinkType_value = map[string]int32{
		"IntraOrbitSatelliteLink": 0,
		"InterOrbitSatelliteLink": 1,
		"GroundSatelliteLink":     2,
		"AccessLink":              3,
		"BackboneLink":            4,
	}
)

func (x NetworkLinkType) Enum() *NetworkLinkType {
	p := new(NetworkLinkType)
	*p = x
	return p
}

func (x NetworkLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[2].Descriptor()
}

func (NetworkLinkType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[2]
}

func (x NetworkLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkLinkType.Descriptor instead.
func (NetworkLinkType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{2}
}

var File_entities_proto protoreflect.FileDescriptor

const file_entities_proto_rawDesc = "" +
	"\n" +
	"\x0eentities.proto*E\n" +
	"\x11NetworkNodeStatus\x12\t\n" +
	"\x05Logic\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\v\n" +
	"\aStarted\x10\x03*\x9e\x02\n" +
	"\x0fNetworkNodeType\x12\x13\n" +
	"\x0fNormalSatellite\x10\x00\x12\x0f\n" +
	"\vEtcdService\x10\x01\x12\x13\n" +
	"\x0fPositionService\x10\x02\x12\n" +
	"\n" +
	"\x06Router\x10\x03\x12\x0e\n" +
	"\n" +
	"NormalNode\x10\x04\x12\x11\n" +
	"\rConsensusNode\x10\x05\x12\x12\n" +
	"\x0eChainMakerNode\x10\x06\x12\x11\n" +
	"\rMaliciousNode\x10\a\x12\v\n" +
	"\aLirNode\x10\b\x12\f\n" +
	"\bEntrance\x10\t\x12\x11\n" +
	"\rGroundStation\x10\n" +
	"\x12\x12\n" +
	"\x0eFabricPeerNode\x10\v\x12\x13\n" +
	"\x0fFabricOrderNode\x10\f\x12\x10\n" +
	"\fLiRSatellite\x10\r\x12\x11\n" +
	"\rFiscoBcosNode\x10\x0e*\x86\x01\n" +
	"\x0fNetworkLinkType\x12\x1b\n" +
	"\x17IntraOrbitSatelliteLink\x10\x00\x12\x1b\n" +
	"\x17InterOrbitSatelliteLink\x10\x01\x12\x17\n" +
	"\x13GroundSatelliteLink\x10\x02\x12\x0e\n" +
	"\n" +
	"AccessLink\x10\x03\x12\x10\n" +
	"\fBackboneLink\x10\x04B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_entities_proto_rawDescOnce sync.Once
	file_entities_proto_rawDescData []byte
)

func file_entities_proto_rawDescGZIP() []byte {
	file_entities_proto_rawDescOnce.Do(func() {
		file_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)))
	})
	return file_entities_proto_rawDescData
}

var file_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_entities_proto_goTypes = []any{
	(NetworkNodeStatus)(0), // 0: NetworkNodeStatus
	(NetworkNodeType)(0),   // 1: NetworkNodeType
	(NetworkLinkType)(0),   // 2: NetworkLinkType
}
var file_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_proto_init() }
func file_entities_proto_init() {
	if File_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_proto_goTypes,
		DependencyIndexes: file_entities_proto_depIdxs,
		EnumInfos:         file_entities_proto_enumTypes,
	}.Build()
	File_entities_proto = out.File
	file_entities_proto_goTypes = nil
	file_entities_proto_depIdxs = nil
}
