// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: router.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InnerRouterType int32

const (
	InnerRouterType_Normal         InnerRouterType = 0
	InnerRouterType_PathValidation InnerRouterType = 1
)

// Enum value maps for InnerRouterType.
var (
	InnerRouterType_name = map[int32]string{
		0: "Normal",
		1: "PathValidation",
	}
	InnerRouterType_value = map[string]int32{
		"Normal":         0,
		"PathValidation": 1,
	}
)

func (x InnerRouterType) Enum() *InnerRouterType {
	p := new(InnerRouterType)
	*p = x
	return p
}

func (x InnerRouterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InnerRouterType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[0].Descriptor()
}

func (InnerRouterType) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[0]
}

func (x InnerRouterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InnerRouterType.Descriptor instead.
func (InnerRouterType) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

var File_router_proto protoreflect.FileDescriptor

const file_router_proto_rawDesc = "" +
	"\n" +
	"\frouter.proto*1\n" +
	"\x0fInnerRouterType\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\x12\n" +
	"\x0ePathValidation\x10\x01B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_router_proto_rawDescOnce sync.Once
	file_router_proto_rawDescData []byte
)

func file_router_proto_rawDescGZIP() []byte {
	file_router_proto_rawDescOnce.Do(func() {
		file_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)))
	})
	return file_router_proto_rawDescData
}

var file_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_router_proto_goTypes = []any{
	(InnerRouterType)(0), // 0: InnerRouterType
}
var file_router_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_router_proto_init() }
func file_router_proto_init() {
	if File_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_proto_goTypes,
		DependencyIndexes: file_router_proto_depIdxs,
		EnumInfos:         file_router_proto_enumTypes,
	}.Build()
	File_router_proto = out.File
	file_router_proto_goTypes = nil
	file_router_proto_depIdxs = nil
}
