// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: routing.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransmissionType int32

const (
	TransmissionType_UNICAST   TransmissionType = 0
	TransmissionType_MULTIPATH TransmissionType = 1
	TransmissionType_MULTICAST TransmissionType = 2
	TransmissionType_MAB       TransmissionType = 3
)

// Enum value maps for TransmissionType.
var (
	TransmissionType_name = map[int32]string{
		0: "UNICAST",
		1: "MULTIPATH",
		2: "MULTICAST",
		3: "MAB",
	}
	TransmissionType_value = map[string]int32{
		"UNICAST":   0,
		"MULTIPATH": 1,
		"MULTICAST": 2,
		"MAB":       3,
	}
)

func (x TransmissionType) Enum() *TransmissionType {
	p := new(TransmissionType)
	*p = x
	return p
}

func (x TransmissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransmissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_routing_proto_enumTypes[0].Descriptor()
}

func (TransmissionType) Type() protoreflect.EnumType {
	return &file_routing_proto_enumTypes[0]
}

func (x TransmissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransmissionType.Descriptor instead.
func (TransmissionType) EnumDescriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

type RoutingType int32

const (
	RoutingType_NOT_SPECIFIED  RoutingType = 0
	RoutingType_Atlas          RoutingType = 1
	RoutingType_MultipathSelir RoutingType = 2
)

// Enum value maps for RoutingType.
var (
	RoutingType_name = map[int32]string{
		0: "NOT_SPECIFIED",
		1: "Atlas",
		2: "MultipathSelir",
	}
	RoutingType_value = map[string]int32{
		"NOT_SPECIFIED":  0,
		"Atlas":          1,
		"MultipathSelir": 2,
	}
)

func (x RoutingType) Enum() *RoutingType {
	p := new(RoutingType)
	*p = x
	return p
}

func (x RoutingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingType) Descriptor() protoreflect.EnumDescriptor {
	return file_routing_proto_enumTypes[1].Descriptor()
}

func (RoutingType) Type() protoreflect.EnumType {
	return &file_routing_proto_enumTypes[1]
}

func (x RoutingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingType.Descriptor instead.
func (RoutingType) EnumDescriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto*F\n" +
	"\x10TransmissionType\x12\v\n" +
	"\aUNICAST\x10\x00\x12\r\n" +
	"\tMULTIPATH\x10\x01\x12\r\n" +
	"\tMULTICAST\x10\x02\x12\a\n" +
	"\x03MAB\x10\x03*?\n" +
	"\vRoutingType\x12\x11\n" +
	"\rNOT_SPECIFIED\x10\x00\x12\t\n" +
	"\x05Atlas\x10\x01\x12\x12\n" +
	"\x0eMultipathSelir\x10\x02B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_routing_proto_goTypes = []any{
	(TransmissionType)(0), // 0: TransmissionType
	(RoutingType)(0),      // 1: RoutingType
}
var file_routing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		EnumInfos:         file_routing_proto_enumTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
