// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: sec_path_mab.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecPathMabStrategy int32

const (
	SecPathMabStrategy_FIXED_BATCH   SecPathMabStrategy = 0
	SecPathMabStrategy_DYNAMIC_BATCH SecPathMabStrategy = 1
)

// Enum value maps for SecPathMabStrategy.
var (
	SecPathMabStrategy_name = map[int32]string{
		0: "FIXED_BATCH",
		1: "DYNAMIC_BATCH",
	}
	SecPathMabStrategy_value = map[string]int32{
		"FIXED_BATCH":   0,
		"DYNAMIC_BATCH": 1,
	}
)

func (x SecPathMabStrategy) Enum() *SecPathMabStrategy {
	p := new(SecPathMabStrategy)
	*p = x
	return p
}

func (x SecPathMabStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecPathMabStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_sec_path_mab_proto_enumTypes[0].Descriptor()
}

func (SecPathMabStrategy) Type() protoreflect.EnumType {
	return &file_sec_path_mab_proto_enumTypes[0]
}

func (x SecPathMabStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecPathMabStrategy.Descriptor instead.
func (SecPathMabStrategy) EnumDescriptor() ([]byte, []int) {
	return file_sec_path_mab_proto_rawDescGZIP(), []int{0}
}

type SecPathMabTopologyType int32

const (
	SecPathMabTopologyType_NON_LINEAR_TEST_TOPOLOGY SecPathMabTopologyType = 0
	SecPathMabTopologyType_LINEAR_TEST_TOPOLOGY     SecPathMabTopologyType = 1
)

// Enum value maps for SecPathMabTopologyType.
var (
	SecPathMabTopologyType_name = map[int32]string{
		0: "NON_LINEAR_TEST_TOPOLOGY",
		1: "LINEAR_TEST_TOPOLOGY",
	}
	SecPathMabTopologyType_value = map[string]int32{
		"NON_LINEAR_TEST_TOPOLOGY": 0,
		"LINEAR_TEST_TOPOLOGY":     1,
	}
)

func (x SecPathMabTopologyType) Enum() *SecPathMabTopologyType {
	p := new(SecPathMabTopologyType)
	*p = x
	return p
}

func (x SecPathMabTopologyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecPathMabTopologyType) Descriptor() protoreflect.EnumDescriptor {
	return file_sec_path_mab_proto_enumTypes[1].Descriptor()
}

func (SecPathMabTopologyType) Type() protoreflect.EnumType {
	return &file_sec_path_mab_proto_enumTypes[1]
}

func (x SecPathMabTopologyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecPathMabTopologyType.Descriptor instead.
func (SecPathMabTopologyType) EnumDescriptor() ([]byte, []int) {
	return file_sec_path_mab_proto_rawDescGZIP(), []int{1}
}

var File_sec_path_mab_proto protoreflect.FileDescriptor

const file_sec_path_mab_proto_rawDesc = "" +
	"\n" +
	"\x12sec_path_mab.proto*8\n" +
	"\x12SecPathMabStrategy\x12\x0f\n" +
	"\vFIXED_BATCH\x10\x00\x12\x11\n" +
	"\rDYNAMIC_BATCH\x10\x01*P\n" +
	"\x16SecPathMabTopologyType\x12\x1c\n" +
	"\x18NON_LINEAR_TEST_TOPOLOGY\x10\x00\x12\x18\n" +
	"\x14LINEAR_TEST_TOPOLOGY\x10\x01B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_sec_path_mab_proto_rawDescOnce sync.Once
	file_sec_path_mab_proto_rawDescData []byte
)

func file_sec_path_mab_proto_rawDescGZIP() []byte {
	file_sec_path_mab_proto_rawDescOnce.Do(func() {
		file_sec_path_mab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sec_path_mab_proto_rawDesc), len(file_sec_path_mab_proto_rawDesc)))
	})
	return file_sec_path_mab_proto_rawDescData
}

var file_sec_path_mab_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sec_path_mab_proto_goTypes = []any{
	(SecPathMabStrategy)(0),     // 0: SecPathMabStrategy
	(SecPathMabTopologyType)(0), // 1: SecPathMabTopologyType
}
var file_sec_path_mab_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sec_path_mab_proto_init() }
func file_sec_path_mab_proto_init() {
	if File_sec_path_mab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sec_path_mab_proto_rawDesc), len(file_sec_path_mab_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sec_path_mab_proto_goTypes,
		DependencyIndexes: file_sec_path_mab_proto_depIdxs,
		EnumInfos:         file_sec_path_mab_proto_enumTypes,
	}.Build()
	File_sec_path_mab_proto = out.File
	file_sec_path_mab_proto_goTypes = nil
	file_sec_path_mab_proto_depIdxs = nil
}
