ubuntu:
	docker build -t ubuntu_with_software:latest -f ./ubuntu_with_software/Dockerfile ./ubuntu_with_software

python_env:
	docker build -t python_env:latest -f ./python_env/Dockerfile ./python_env

go_env:
	docker build -t go_env:latest -f ./go_env/Dockerfile ./go_env

normal_satellite:
	docker build -t normal_satellite:latest -f ./normal_satellite/Dockerfile ./normal_satellite