ubuntu:
	docker build -t ubuntu_with_software:latest -f ./build_ubuntu_with_software/Dockerfile ./build_ubuntu_with_software

python_env:
	docker build -t python_env:latest -f ./build_python_env/Dockerfile ./build_python_env

go_env:
	docker build -t go_env:latest -f ./build_go_env/Dockerfile ./build_go_env

normal_satellite:
	docker build -t normal_satellite:latest -f ./build_normal_satellite/Dockerfile ./build_normal_satellite