// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.20.3
// source: link/link.proto

package link

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LinkType int32

const (
	LinkType_LINK_TYPE_INTER_SATELLITE_LINK  LinkType = 0
	LinkType_LINK_TYPE_GROUND_SATELLITE_LINK LinkType = 1
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_INTER_SATELLITE_LINK",
		1: "LINK_TYPE_GROUND_SATELLITE_LINK",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_INTER_SATELLITE_LINK":  0,
		"LINK_TYPE_GROUND_SATELLITE_LINK": 1,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_link_link_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_link_link_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_link_link_proto_rawDescGZIP(), []int{0}
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            LinkType `protobuf:"varint,1,opt,name=type,proto3,enum=LinkType" json:"type,omitempty"`
	Id              int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	SourceNodeId    int32    `protobuf:"varint,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId    int32    `protobuf:"varint,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	SourceIfaceName string   `protobuf:"bytes,5,opt,name=source_iface_name,json=sourceIfaceName,proto3" json:"source_iface_name,omitempty"`
	TargetIfaceName string   `protobuf:"bytes,6,opt,name=target_iface_name,json=targetIfaceName,proto3" json:"target_iface_name,omitempty"`
	Bandwidth       float32  `protobuf:"fixed32,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Delay           float32  `protobuf:"fixed32,8,opt,name=delay,proto3" json:"delay,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_link_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_link_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetType() LinkType {
	if x != nil {
		return x.Type
	}
	return LinkType_LINK_TYPE_INTER_SATELLITE_LINK
}

func (x *Link) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Link) GetSourceNodeId() int32 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *Link) GetTargetNodeId() int32 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *Link) GetSourceIfaceName() string {
	if x != nil {
		return x.SourceIfaceName
	}
	return ""
}

func (x *Link) GetTargetIfaceName() string {
	if x != nil {
		return x.TargetIfaceName
	}
	return ""
}

func (x *Link) GetBandwidth() float32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Link) GetDelay() float32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

var File_link_link_proto protoreflect.FileDescriptor

var file_link_link_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8d, 0x02, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x49, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x2a, 0x53, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x1e, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x5f, 0x53, 0x41, 0x54, 0x45, 0x4c, 0x4c, 0x49, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x10,
	0x00, 0x12, 0x23, 0x0a, 0x1f, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x53, 0x41, 0x54, 0x45, 0x4c, 0x4c, 0x49, 0x54, 0x45, 0x5f,
	0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6c, 0x69, 0x6e, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_link_link_proto_rawDescOnce sync.Once
	file_link_link_proto_rawDescData = file_link_link_proto_rawDesc
)

func file_link_link_proto_rawDescGZIP() []byte {
	file_link_link_proto_rawDescOnce.Do(func() {
		file_link_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_link_proto_rawDescData)
	})
	return file_link_link_proto_rawDescData
}

var file_link_link_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_link_link_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_link_link_proto_goTypes = []interface{}{
	(LinkType)(0), // 0: LinkType
	(*Link)(nil),  // 1: Link
}
var file_link_link_proto_depIdxs = []int32{
	0, // 0: Link.type:type_name -> LinkType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_link_link_proto_init() }
func file_link_link_proto_init() {
	if File_link_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_link_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_link_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_link_link_proto_goTypes,
		DependencyIndexes: file_link_link_proto_depIdxs,
		EnumInfos:         file_link_link_proto_enumTypes,
		MessageInfos:      file_link_link_proto_msgTypes,
	}.Build()
	File_link_link_proto = out.File
	file_link_link_proto_rawDesc = nil
	file_link_link_proto_goTypes = nil
	file_link_link_proto_depIdxs = nil
}
